/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IName } from "./components/primaries-icon/icon-types";
export namespace Components {
    interface PrimariesIcon {
        /**
          * name of the Icon, exactly as the figma
         */
        "icon": IName;
        /**
          * size of the bounding box of the icon
         */
        "size": number;
    }
}
declare global {
    interface HTMLPrimariesIconElement extends Components.PrimariesIcon, HTMLStencilElement {
    }
    var HTMLPrimariesIconElement: {
        prototype: HTMLPrimariesIconElement;
        new (): HTMLPrimariesIconElement;
    };
    interface HTMLElementTagNameMap {
        "primaries-icon": HTMLPrimariesIconElement;
    }
}
declare namespace LocalJSX {
    interface PrimariesIcon {
        /**
          * name of the Icon, exactly as the figma
         */
        "icon"?: IName;
        /**
          * size of the bounding box of the icon
         */
        "size"?: number;
    }
    interface IntrinsicElements {
        "primaries-icon": PrimariesIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "primaries-icon": LocalJSX.PrimariesIcon & JSXBase.HTMLAttributes<HTMLPrimariesIconElement>;
        }
    }
}
